# Generated by Django 4.1.5 on 2023-01-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universitet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('talaba_soni', models.PositiveIntegerField()),
                ('sana', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
