# Generated by Django 4.1.5 on 2023-01-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('bino', models.CharField(max_length=20)),
                ('rahbar', models.CharField(max_length=20)),
                ('fan_soni', models.CharField(max_length=15)),
            ],
        ),
    ]
