# Generated by Django 4.1.5 on 2023-01-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_fakultet'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitet',
            name='yillik',
            field=models.CharField(choices=[('3 yiilik', '3 yillik'), ('4 yiilik', '4 yillik')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='universitet',
            name='nom',
            field=models.CharField(blank=True, max_length=50, verbose_name='Universitet'),
        ),
    ]
