# Generated by Django 4.1.5 on 2023-01-09 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_universitet_yillik_alter_universitet_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imtihon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('joy', models.CharField(max_length=50)),
                ('davomiylik', models.SmallIntegerField()),
                ('fk_universitet', models.ForeignKey(null='a', on_delete=django.db.models.deletion.CASCADE, to='asosiy.universitet', verbose_name='Universitet')),
            ],
        ),
    ]
