# Generated by Django 4.1.5 on 2023-01-11 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_imtihon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imtihon',
            name='davomiylik',
        ),
        migrations.RemoveField(
            model_name='imtihon',
            name='fk_universitet',
        ),
        migrations.RemoveField(
            model_name='imtihon',
            name='sana',
        ),
        migrations.AddField(
            model_name='imtihon',
            name='universitet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asosiy.universitet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imtihon',
            name='vaqt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='universitet',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='universitet',
            name='nom',
            field=models.CharField(blank=True, max_length=50, verbose_name="Universitet to'liq nomi"),
        ),
        migrations.AlterField(
            model_name='universitet',
            name='sana',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='universitet',
            name='talaba_soni',
            field=models.PositiveIntegerField(default=1500, verbose_name='Umumiy talabalar soni'),
        ),
        migrations.AlterField(
            model_name='universitet',
            name='yillik',
            field=models.CharField(choices=[('3 yillik', '3 yillik'), ('4 yillik', '4 yillik'), ('5 yillik', '5 yillik')], max_length=10, null=True),
        ),
    ]
