# Generated by Django 4.1.5 on 2023-01-13 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0005_remove_imtihon_davomiylik_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, verbose_name="Kitobning to'liq nomi")),
                ('narx', models.CharField(blank=True, max_length=50, verbose_name='Kitobning narxi')),
                ('kelgan_sana', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nashriyot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, verbose_name="Nashriyotning to'liq nomi")),
                ('manzil', models.CharField(blank=True, max_length=50, verbose_name='Manzil')),
            ],
        ),
        migrations.CreateModel(
            name='Sotuv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('kitob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.kitob')),
            ],
        ),
        migrations.CreateModel(
            name='Sotuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Fakultet',
        ),
        migrations.DeleteModel(
            name='Imtihon',
        ),
        migrations.DeleteModel(
            name='Universitet',
        ),
        migrations.AddField(
            model_name='sotuv',
            name='sotuvchi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.sotuvchi'),
        ),
        migrations.AddField(
            model_name='kitob',
            name='nashriyoti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.nashriyot'),
        ),
    ]
